!include style.puml

!includesub cantilever_subsystem.puml!component
!includesub afm_components.puml!dynamic_mode_components

' Feedback Components '
!includesub afm_components.puml!feedback_subsystem
note bottom of feedback_subsystem
  Maintains signal amplitude by varying z-height.
end note

cs_pspd_out ..> li_u_in
sg_si_out .u.> li_u_refi_in
sg_sq_out .u.> li_u_refq_in
sg_si_out ..> cs_piezo_in: "<latex>S_i[\sim]</latex>"

li_amp_out ..> sm_s_in
pi_u_t_out ..> cs_piezo_in: "<latex>S_i[-]</latex>"

li_phase_out ..> sg_phase_in
