!include style.puml

!startsub component
component "Cantilever Subsystem" as cantilever_subsystem {
  component Laser as cs_laser
  component Cantilever as cs_cantilever
  component PSPD as cs_pspd
  component "Piezo" as cs_piezo
  interface "<latex>R_z</latex>" <<output>> as cs_pspd_out
  interface "<latex>S_z</latex>" <<input>> as cs_piezo_in

  cs_laser --> cs_cantilever
  cs_cantilever -u-> cs_pspd
  cs_piezo -u-> cs_cantilever
  cs_pspd -> cs_pspd_out
  cs_piezo_in -> cs_piezo
}
!endsub
