!include style.puml
'left to right direction

interface "<latex>U_{in}[\sim]</latex>" <<input>> as u_in

component "Lock-In Amplifier" as lockin {
  interface "<latex>\omega_{ref}</latex>" <<param>> as ang_freq
  interface "<latex>T</latex>" <<param>> as avg_cycles
  rectangle "Oscillator" as sine_gen
  rectangle "<latex>|\textbf{X+Y}|_2</latex>" as l2_norm
  rectangle "<latex>\theta=atan(\frac{\textbf{Y}}{\textbf{X}})</latex>" as phase_calc

  ang_freq -> sine_gen

  package " " <<layout>> as integrator_blocks {
    package " " <<layout>> as integrator_block_sin {
      storage X as x_sin
      rectangle "<latex>\frac{1}{T}\int_{t-T}^{t}dt</latex>" as integrator_sin

      u_in -> x_sin
      sine_gen --> x_sin: "<latex>sin(\omega t)</latex>"
      x_sin --> integrator_sin
    }

    package " " <<layout>> as integrator_block_cos {
      storage X as x_cos
      rectangle "<latex>\frac{1}{T}\int_{t-T}^{t}dt</latex>" as integrator_cos

      u_in -> x_cos
      sine_gen --> x_cos: "<latex>cos(\omega t)</latex>"
      x_cos --> integrator_cos
    }
  }

  avg_cycles -> integrator_sin

  integrator_sin --> l2_norm
  integrator_cos --> l2_norm
  integrator_sin --> phase_calc
  integrator_cos --> phase_calc
}

interface "<latex>V_{sig}[-]</latex>" <<output>> as v_sig
interface "<latex>\varphi[-]</latex>" <<output>> as phi

l2_norm --> v_sig
phase_calc --> phi
