!include style.puml

!startsub component
interface "e(t)" <<input>> as pi_e_t_in
interface "u(t)" <<output>> as pi_u_t_out
component "PID Controller" as pid_simple

pi_e_t_in -> pid_simple
pid_simple -> pi_u_t_out
!endsub
