!include style.puml
 left to right direction

 !startsub component
 interface "<latex>S_{in[0:N]}</latex>" <<input>> as s_in

 component "Multi-Source Setpoint Control" as source_mixer {
   rectangle "\n<&layers>" as single_source_block #line:grey;line.dashed {
     rectangle "<latex>LPF_i</latex>" as lpf
     rectangle "<latex>TR_i</latex>" as tr
     storage "<latex>\Delta</latex>" as delta
     interface "<latex>y_{sp}_{i}</latex>" <<param>> as sp_i
     interface "<latex>G_i</latex>" <<param>> as g_i
     storage "X" as gain

     lpf --> tr
     tr --> delta
     sp_i --> delta
     delta --> gain
     g_i --> gain
   }
 }

 s_in --> lpf

 storage "<latex>\textbf{\Sigma}</latex>" as sum
 interface "<latex>S_{\Delta}(t)</latex>" <<output>> as s_del

 gain --> sum: "<&layers>\n"
 sum --> s_del
!endsub
