!include style.puml

!startsub component
component "Source Mixer" as source_mixer_simple
interface "<latex>S_{in[0:N]}</latex>" <<input>> as y_ts
interface "<latex>S_{\Delta}</latex>" <<output>> as s_del

y_ts -> source_mixer_simple
'r_ts -u-> source_mixer_simple
source_mixer_simple -> s_del
!endsub
