!include style.puml

!startsub component
component "Multi-Source \nSetpoint Control" as source_mixer_simple
interface "<latex>S_{in[0:N]}</latex>" <<input>> as sm_s_in
interface "<latex>S_{\Delta}</latex>" <<output>> as sm_s_del_out

sm_s_in -> source_mixer_simple
source_mixer_simple -> sm_s_del_out
!endsub
