<style>
  .input {
    BackgroundColor LightBlue
  }
  .output {
    BackgroundColor Pink
  }
  .param {
    BackgroundColor DarkSeaGreen
  }
  .layout {
    LineColor Transparent
  }
  .center {
    HorizontalAlignment center
  }
  .left {
    HorizontalAlignment left
  }
  .right {
    HorizontalAlignment right
  }
</style>

  skinparam componentStyle rectangle
  'skinparam linetype ortho
  hide stereotype
