skinparam componentStyle uml2
skinparam interface {
  backgroundColor<<input>> lightblue
  backgroundColor<<output>> pink
  backgroundColor<<param>> darkseagreen
}

skinparam package {
  borderColor<<layout>> transparent
}

skinparam defaultTextAlignment<<right>> right
skinparam defaultTextAlignment<<left>> left
skinparam defaultTextAlignment<<center>> center

hide stereotype
